name: "Hassception"
description: "Home Assistant inside Home Assistant!"
version: "1.0.29"
slug: "hassception"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8999
ports:
  8999/tcp: 8999

map:
  - "config:rw"