name: "Hassception"
description: "Home Assistant inside Home Assistant!"
version: "1.0.23"
slug: "hassception"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8123
ports:
  8123/tcp: null

map:
  - "config:rw"