name: "Hassception"
description: "Home Assistant inside Home Assistant!"
version: "1.0.13"
slug: "hassception"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8123/tcp: 8124
map:
  - "config:rw"