name: "Hassception"
description: "Home Assistant inside Home Assistant!"
version: "1.0.26"
slug: "hassception"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ports:
  8123/tcp: 8099

map:
  - "config:rw"