name: "Hassception"
description: "Home Assistant inside Home Assistant!"
version: "1.0.28"
slug: "hassception"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8124
ports:
  8124/tcp: 8124

map:
  - "config:rw"